[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://ctdugdxjjpeneznwplde.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_U7RbOOi7JhiRFttUZBYDuw_LUJtTk5c"

[[plugins]]
  package = "@netlify/plugin-nextjs"